import {
  DSA_FONT_FAMILY_BASIC,
  DSA_FONT_SIZE_XXXL,
  DSA_FONT_WEIGHT_BOLD,
  DSA_LETTER_SPACING_WIDE,
  DSA_LINE_HEIGHT_TIGHT,
} from './build/tokens/ts/tokens';

export const BASIC_HEADING_H1_STYLE = {
  fontFamily: DSA_FONT_FAMILY_BASIC,
  fontSize: DSA_FONT_SIZE_XXXL,
  fontWeight: DSA_FONT_WEIGHT_BOLD,
  letterSpacing: DSA_LETTER_SPACING_WIDE,
  lineHeight: DSA_LINE_HEIGHT_TIGHT,
};
